# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: m4d-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: m4d-

resources:
- authentication.yaml
- outbound_traffic_policy.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
