{{ if .Values.razee }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: razee-credentials
data:
  {{ if .Values.razee.url }}
  RAZEE_URL: {{ .Values.razee.url | b64enc }}
  {{ end }}
  {{ if .Values.razee.user }}
  RAZEE_USER: {{ .Values.razee.user | b64enc }}
  {{ end }}
  {{ if .Values.razee.password }}
  RAZEE_PASSWORD: {{ .Values.razee.password | b64enc }}
  {{ end }}
  {{ if .Values.razee.apiKey }}
  API_KEY: {{ .Values.razee.apiKey | b64enc }}
  {{ end }}
  {{ if .Values.razee.iamKey }}
  IAM_API_KEY: {{ .Values.razee.iamKey | b64enc }}
  {{ end }}
{{ end }}