# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - "--enable-leader-election"
        - "--enable-all-controllers"
        image: controller:latest
        name: manager
        imagePullPolicy: Always
        env:
          - name: ENABLE_WEBHOOKS
            value: "true"
          - name: MOVER_IMAGE
            value: "ghcr.io/the-mesh-for-data/mover:latest"
          - name: IMAGE_PULL_POLICY
            value: "Always"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
