# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.m4d.ibm.com/v1alpha1
kind: BatchTransfer
metadata:
  name: {{ include "m4d-implicit-copy-batch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "m4d-implicit-copy-batch.name" . }}
    helm.sh/chart: {{ include "m4d-implicit-copy-batch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
{{ end }}
spec:
  source:
    {{ if .Values.copy.source.connection.s3 }}
    s3:
      endpoint: "{{ .Values.copy.source.connection.s3.endpoint }}"
      bucket: "{{ .Values.copy.source.connection.s3.bucket }}"
      objectKey: "{{ .Values.copy.source.connection.s3.object_key }}"
      dataFormat: "{{ .Values.copy.source.format }}"
      vaultPath: "{{ .Values.copy.source.credentialLocation }}"
    {{ end }}
    {{ if .Values.copy.source.connection.db2 }}
    database:
      table: "{{ .Values.copy.source.connection.db2.table }}"
      db2URL: "jdbc:db2://{{ .Values.copy.source.connection.db2.url }}:{{ .Values.copy.source.connection.db2.port }}/{{ .Values.copy.source.connection.db2.database }}:sslConnection={{ .Values.copy.source.connection.db2.ssl }};"
      vaultPath: "{{ .Values.copy.source.credentialLocation }}"
    {{ end }}
  destination:
    {{ if .Values.copy.destination.connection.s3 }}
    s3:
      endpoint: "{{ .Values.copy.destination.connection.s3.endpoint }}"
      bucket: "{{ .Values.copy.destination.connection.s3.bucket }}"
      objectKey: "{{ .Values.copy.destination.connection.s3.object_key }}"
      dataFormat: "{{ .Values.copy.destination.format }}"
      vaultPath: "{{ .Values.copy.destination.credentialLocation }}"
    {{ end }}
    {{ if .Values.copy.destination.connection.db2 }}
    database:
      table: "{{ .Values.copy.destination.connection.db2.table }}"
      db2URL: "jdbc:db2://{{ .Values.copy.destination.connection.db2.url }}:{{ .Values.copy.destination.connection.db2.port }}/{{ .Values.copy.destination.connection.db2.database }}:sslConnection={{ .Values.copy.destination.connection.db2.ssl }};"
      vaultPath: "{{ .Values.copy.destination.credentialLocation }}"
    {{ end }}
  {{ if .Values.copy.transformations }}
  transformation:
  {{ range .Values.copy.transformations }}
  {{ if eq .id "redact-ID" }}
  - action: "RedactColumns"
    name: "redacting column: {{ .args.column_name }}"
    columns: [ {{ .args.column_name | quote }} ]
    options:
      redactValue: "XXXXXX"
  {{ end }}
  {{ if eq .id "removed-ID" }}
  - action: "RemoveColumns"
    name: "redacting column: {{ .args.column_name }}"
    columns: [ "{{ .args.column_name }}" ]
  {{ end }}
  {{ end }}
  {{ end }}
  {{ if .Values.image }}
  image: {{ .Values.image | quote }}
  {{ end }}
  {{ if .Values.imagePullPolicy }}
  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
  {{ end }}
  noFinalizer: {{ .Values.noFinalizer }}
