# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Default values for m4d-db2wh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: "ghcr.io/the-mesh-for-data/mover:latest"
imagePullPolicy: null
noFinalizer: "false"

copy:
  # copies from source
  source:
    connection:
      db2:
        table: ""
        url: ""
        port: ""
        database: ""
        ssl: false
    credentialLocation: ""

  # copies to destination
  destination:
    connection:
      s3:
        endpoint: ""
        bucket: ""
        object_key: ""
    format: ""
    credentialLocation: ""