# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30333  # Razee dash API node port in K8s
    hostPort: 3333  # Razee dash API on host
  - containerPort: 30080  # Razee dash UI node port in K8s
    hostPort: 8080  # Razee dash UI on host
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["https://kind-registry:5000"]