# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.m4d.ibm.com/v1alpha1
kind: StreamTransfer
metadata:
  name: {{ .Release.Name }}
spec:
  source:
    kafka:
      kafkaBrokers: "{{ .Values.copy.source.connection.kafka.bootstrap_servers }}"
      schemaRegistryURL: "{{ .Values.copy.source.connection.kafka.schema_registry }}"
      kafkaTopic: "{{ .Values.copy.source.connection.kafka.topic_name }}"
      dataFormat: "{{ .Values.copy.source.format }}"
      # user: "demo-consumer" # can be taken from vault
      # password: "" # can be taken from vault
      createSnapshot: false
      sslTruststore: "{{ .Values.copy.source.connection.kafka.ssl_truststore }}"
      sslTruststoreLocation: /opt/spark/work-dir/ca.p12
      sslTruststorePassword: "{{ .Values.copy.source.connection.kafka.ssl_truststore_password }}"
      securityProtocol: "{{ .Values.copy.source.connection.kafka.security_protocol }}"
      saslMechanism: "{{ .Values.copy.source.connection.kafka.sasl_mechanism }}"
      keyDeserializer: "{{ .Values.copy.source.connection.kafka.key_deserializer }}"
      valueDeserializer: "{{ .Values.copy.source.connection.kafka.value_deserializer }}"
      vaultPath: "{{ .Values.copy.source.credentialLocation }}"
  destination:
    s3:
      endpoint: "{{ .Values.copy.destination.connection.s3.endpoint }}"
      bucket: "{{ .Values.copy.destination.connection.s3.bucket }}"
      objectKey: "{{ .Values.copy.destination.connection.s3.object_key }}"
      dataFormat: "{{ .Values.copy.destination.format }}"
      vaultPath: "{{ .Values.copy.destination.credentialLocation }}"
  {{ if .Values.copy.transformations }}
  transformation:
  {{ range .Values.copy.transformations }}
  {{ if eq .id "redact-ID" }}
  - action: "RedactColumns"
    name: "redacting column: {{ .args.column_name }}"
    columns: [ {{ .args.column_name | quote }} ]
    options:
      redactValue: "XXXXXX"
  {{ end }}
  {{ if eq .id "removed-ID" }}
  - action: "RemoveColumns"
    name: "redacting column: {{ .args.column_name }}"
    columns: [ "{{ .args.column_name }}" ]
  {{ end }}
  {{ end }}
  {{ end }}
  triggerInterval: "10 seconds"
  {{ if .Values.image }}
  image: {{ .Values.image | quote }}
  {{ end }}
  {{ if .Values.imagePullPolicy }}
  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
  {{ end }}
  noFinalizer: {{ .Values.noFinalizer }}
