# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# This patch sets the imagePullPolicy of the manager to Always.
# This ensures that the image is always reloaded.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: integration-tests
        image: alpine/socat:latest
        command:
        - socat
        - TCP4-LISTEN:5000,fork
        - TCP4:kind-registry:5000
      - name: manager
        imagePullPolicy: Always
        env:
        - name: ENABLE_WEBHOOKS
          value: "true"
        - name: MOVER_IMAGE
          value: "localhost:5000/m4d-system/dummy-mover:latest"
        - name: IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: NO_FINALIZER
          value: "false"
        - name: GODEBUG
          value: "x509ignoreCN=0"
