baseURL = "/"
languageCode = "en-us"
title = "The Mesh for Data"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableemoji = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
   name = "Contribute"
   url = "/contribute/"
   weight = 3

[params]
  github_link = 'https://github.com/IBM/the-mesh-for-data'
  mainSections = ["docs", "contribute"]
  google_analytics_id=""

  homepage_button_left_link = '/docs/overview/what-is/'
  homepage_button_left_text = 'Learn more'
  homepage_button_left_icon = 'fas fa-book-reader'

  homepage_button_right_link = '/docs/setup/quickstart/'
  homepage_button_right_text = 'Quick start'
  homepage_button_right_icon = 'fas fa-download'

  homepage_intro = 'The Mesh for Data is a cloud-native platform to control data access and data usage across an organization.'
#  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "The Mesh for Data is a cloud-native platform to solve your data access problems."
    meta_og_title = "The Mesh for Data"
    meta_og_type = "website"
    meta_og_url = "https://ibm.github.io/the-mesh-for-data/"
    #meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "The Mesh for Data is a cloud-native platform to solve your data access problems."
    meta_twitter_card = "summary"
    #meta_twitter_site = "@themeshfordata"
    #meta_twitter_creator = "@themeshfordata"

  [params.logo]
    mobile = "/images/logo.svg"
    standard  = "/images/logo.svg"

# TODO: this is only used for tables, should create a partial instead
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
