# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.m4d.ibm.com/v1alpha1
kind: BatchTransfer
metadata:
  name: {{ .Release.Name }}
spec:
  source:
    s3:
      endpoint: "{{ .Values.copy.source.connection.s3.endpoint }}"
      bucket: "{{ .Values.copy.source.connection.s3.bucket }}"
      objectKey: "{{ .Values.copy.source.connection.s3.object_key }}"
      dataFormat: "{{ .Values.copy.source.format }}"
      vaultPath: "{{ .Values.copy.source.credentialLocation }}"
  destination:
    s3:
      endpoint: "{{ .Values.copy.destination.connection.s3.endpoint }}"
      bucket: "{{ .Values.copy.destination.connection.s3.bucket }}"
      objectKey: "{{ .Values.copy.destination.connection.s3.object_key }}"
      dataFormat: "{{ .Values.copy.destination.format }}"
      vaultPath: "{{ .Values.copy.destination.credentialLocation }}"
  transformation:
  {{ range .Values.copy.transformations }}
  {{ if eq .id "redact-ID" }}
  - action: "RedactColumns"
    name: "redacting column: {{ .args.column_name }}"
    columns: [ {{ .args.column_name | quote }} ]
    options:
      redactValue: "XXXXXX"
  {{ end }}
  {{ if eq .id "removed-ID" }}
  - action: "RemoveColumns"
    name: "redacting column: {{ .args.column_name }}"
    columns: [ "{{ .args.column_name }}" ]
  {{ end }}
  {{ end }}
  {{ if .Values.image }}
  image: {{ .Values.image | quote }}
  {{ end }}
  {{ if .Values.imagePullPolicy }}
  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
  {{ end }}
  noFinalizer: {{ .Values.noFinalizer }}
